Remove getVibrate and getSoundEnabled apis and logics
OneSignal/OneSignal-Android-SDK pull request #1188
Opened 2020-10-14 22:41 UTC by Jeasmine

2020-10-14 23:44 UTC, jkasten2 requested changes

2020-10-14 23:44 UTC, jkasten2 commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java
> -      if (OneSignal.getVibrate() && fcmJson.optInt("vib", 1) == 1) {
We just want to remove the `OneSignal.getVibrate()` call here. As a backwards compatibility for pre-O devices the OneSignal backend will still send "vib" depending if the Notification Category has this set.

2020-10-14 23:44 UTC, jkasten2 commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java
> -   private static boolean isSoundEnabled(JSONObject fcmJson) {
Keep this method, just remove the `OneSignal.getSoundEnabled();` check. Same reason noted above about the Android Notification Categories

2020-10-15 18:06 UTC, jkasten2 approved these changes

2020-10-15 18:30 UTC, jkasten2 commented
Flaky tests notes. One failed on `testAfterLastInAppTimeIsDisplayed` and the other on `testNotificationWillShowInForegroundHandler_notCallCompleteShowsNotificationAfterTimeout`

2020-10-15 18:35 UTC, Jeasmine commented
> Flaky tests notes. One failed on `testAfterLastInAppTimeIsDisplayed` and the other on `testNotificationWillShowInForegroundHandler_notCallCompleteShowsNotificationAfterTimeout`

noted!

2020-10-15 18:35 UTC, merged