Add auth hash to external Id
OneSignal/OneSignal-Android-SDK pull request #1210
Opened 2020-11-12 19:22 UTC by Jeasmine

* Add auth to setExternalId
* Add tests for new functionality

2020-11-16 17:36 UTC, jkasten2 approved these changes

2020-11-17 16:35 UTC, jkasten2 requested changes
Need to add `require_user_id_auth` to remote params

2020-11-17 16:35 UTC, jkasten2 commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java
> +            if (remoteParams != null && remoteParams.useEmailAuth && externalIdAuthHash == null) {
`remoteParams.useEmailAuth` should be ` remoteParams.useUserIdAuth`

2020-11-17 20:11 UTC, emawby requested changes

2020-11-17 20:11 UTC, emawby commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java
> +            String internalExternalIdAuthHash = externalIdAuthHash;
Can we change the name of internalExternalIdAuthHash? Is the only change we are making is making it all lower case? If that is the case maybe include the lowercase aspect in the name?

2020-11-20 19:58 UTC, jkasten2 approved these changes
`external_user_id_auth_hash` is correctly added here so I think it looks good to me.

2020-11-20 21:32 UTC, merged