Fix direct tracking
OneSignal/OneSignal-Android-SDK pull request #1244
Opened 2020-12-18 18:48 UTC by Jeasmine

* Direct session tracking is not working when OneSignal opening appllication is disable on the manifest. If the user open the application on the open handler callback no direct session is being track
* Create a complete method under OSNotificationOpenedResult to track direct opening by notification click

2020-12-18 20:32 UTC, emawby requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @rgomezp)

___
*[Examples/OneSignalDemo/app/src/main/AndroidManifest.xml, line 67 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOrX3OLCa92jMI-vY8B:-MOrX3OLCa92jMI-vY8C:b-9dx2ql) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/Examples/OneSignalDemo/app/src/main/AndroidManifest.xml#L67)):*
> ```XML
>             android:value="com.onesignal.sdktest.notification.NotificationServiceExtension" />
> 
>         <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />
> ```

Do we want to commit this change and always test with this setting or is this something we should remove after testing?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java, line 71 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOrY-301CqZKa7ZZ2PI:-MOrY-301CqZKa7ZZ2PJ:bwjqtbs) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L71)):*
> ```Java
>    /**
>     * Method indicating OneSignal that application was opened by user.
>     * This method must be call before startActivity or equivalents are called
> ```

What happens if it is not called before startActivity? With our 5 second timer won't we automatically call complete after startActivity often? Also do we need to update documentation indicating that the opened handler should complete its work in 5 seconds?


<!-- Sent from Reviewable.io -->

2020-12-18 23:07 UTC, rgomezp requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @rgomezp)

___
*[Examples/OneSignalDemo/app/src/main/AndroidManifest.xml, line 67 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOrX3OLCa92jMI-vY8B:-MOryjiN9ctd4MGLc-nU:bsixjol) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/Examples/OneSignalDemo/app/src/main/AndroidManifest.xml#L67)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Do we want to commit this change and always test with this setting or is this something we should remove after testing?
</blockquote></details>

Probably not. Especially since we are just [logging the event](https://documentation.onesignal.com/docs/android-customizations#changing-the-open-action-of-a-notification) in the callback and not actually starting the activity via `startActivity` as indicated [by the docs](https://documentation.onesignal.com/docs/android-customizations#changing-the-open-action-of-a-notification).
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 305 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOs-hM08D7smGnBD7Nq:-MOs-hM08D7smGnBD7Nr:b-y4uj6u) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L305)):*
> ```Java
>       // Fire with the last appEntryState that just ended.
>       void onEntryStateChange(AppEntryAction appEntryState);
>    }
> ```

Nit: newline
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 306 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOs-jNH-X02Qk5gLwi5:-MOs-jNH-X02Qk5gLwi6:b-y4uj6u) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L306)):*
> ```Java
>       void onEntryStateChange(AppEntryAction appEntryState);
>    }
>    private static List<EntryStateListener> entryStateListeners = new ArrayList<>();
> ```

Nit: newline
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java, line 4 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOs5qRf-LE8oeumP-ov:-MOs5qRf-LE8oeumP-ow:bb6ht35) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L4)):*
> ```Java
>  * Modified MIT License
>  *
>  * Copyright 2016 OneSignal
> ```

2020
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java, line 66 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOs5OY13O9dEc3C4ekQ:-MOs5OY29A17nnBYQc1r:b-hbmlzu) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L66)):*
> ```Java
>          }
>       };
>       timeoutHandler.startTimeout(PROCESS_NOTIFICATION_TIMEOUT, timeoutRunnable);
> ```

Can you add a comment expanding on why this timeout is needed, why you chose 5 seconds, and how will this impact existing implementations?

Also would be good to add to the PR for high level.


<!-- Sent from Reviewable.io -->

2020-12-18 23:08 UTC, rgomezp reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @emawby, @Jeasmine, and @jkasten2)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java, line 65 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOs6AgNDz1oi0U-T6lq:-MOs6AgNDz1oi0U-T6lr:bqe7hru) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L65)):*
> ```Java
>             complete(false);
>          }
>       };
> ```

Nit: newine


<!-- Sent from Reviewable.io -->

2020-12-21 19:35 UTC, Jeasmine commented
> > Reviewed 4 of 5 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244)_ status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @rgomezp)
> 
> _[Examples/OneSignalDemo/app/src/main/AndroidManifest.xml, line 67 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOrX3OLCa92jMI-vY8B:-MOrX3OLCa92jMI-vY8C:b-9dx2ql) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/Examples/OneSignalDemo/app/src/main/AndroidManifest.xml#L67)):_
> 
> > ```
> >             android:value="com.onesignal.sdktest.notification.NotificationServiceExtension" />
> > 
> >         <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />
> > ```
> 
> Do we want to commit this change and always test with this setting or is this something we should remove after testing?
> 
> _[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java, line 71 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-MOrY-301CqZKa7ZZ2PI:-MOrY-301CqZKa7ZZ2PJ:bwjqtbs) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/44e231071021b11f31cd99486f9459e4c120546f/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L71)):_
> 
> > ```java
> >    /**
> >     * Method indicating OneSignal that application was opened by user.
> >     * This method must be call before startActivity or equivalents are called
> > ```
> 
> What happens if it is not called before startActivity? With our 5 second timer won't we automatically call complete after startActivity often? Also do we need to update documentation indicating that the opened handler should complete its work in 5 seconds?

thanks for the review! Good catch, we don't want to commit the DISABLE conf. And the comment was old because my first approach was that the user call complete, now it's only called internally

2020-12-21 19:56 UTC, emawby approved these changes

2020-12-21 20:32 UTC, rgomezp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1244#-:-MP6-8l89jG7CW8VFwDv:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @emawby, @Jeasmine, and @jkasten2)



<!-- Sent from Reviewable.io -->

2020-12-22 19:59 UTC, merged