WIP - SMS integration
OneSignal/OneSignal-Android-SDK pull request #1263
Opened 2021-01-25 16:20 UTC by Jeasmine

Current work for SMS integration

2021-02-09 06:13 UTC, aimiebell commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java
>           Log(LOG_LEVEL.ERROR, "Failed to generate JSON for sendPurchases.", t);
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateSynchronizer.java
>                              OneSignal.Log(OneSignal.LOG_LEVEL.INFO, "Device registered, UserId = " + newUserId);
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/LocationIntegrationTests.java
> +        OneSignalInit();
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java
>        OneSignalInit();
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 06:13 UTC, aimiebell commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/SynchronizerIntegrationTests.java
> +        OneSignalInit();
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-03-01 19:54 UTC, jkasten2 requested changes
Overall PR looks good, really like the work put into splitting up the tests here!

> Reviewed 10 of 22 files at r1, 14 of 15 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263#-:-MUhVb0v6c55L7igq1Wj:b-l4dw10)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby, @gonzalonarbaiz, and @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateEmailSynchronizer.java, line 48 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263#-MUhTOdU9PuWHGElokgm:-MUhTJCe1xFDrDsg0VIL:b-jrp6gh) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/f4ae88a007d0b78d053250def7d843fd576dd592/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateEmailSynchronizer.java#L48)):*
> ```Java
> 
>     @Override
>     void logoutSMS() {
> ```

This class has `logoutEmail()` and `logoutSMS()`, I would expect `logoutChannel()` instead. I haven't looked at your other PR so this might be addressed.
___
*[OneSignalSDK/unittest/src/test/java/com/test/onesignal/LocationIntegrationTests.java, line 86 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263#-MUhUkI_4TW8e3KqkkOa:-MUhUkI_4TW8e3KqkkOb:bl5s593) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/f4ae88a007d0b78d053250def7d843fd576dd592/OneSignalSDK/unittest/src/test/java/com/test/onesignal/LocationIntegrationTests.java#L86)):*
> ```Java
> )
> @RunWith(RobolectricTestRunner.class)
> public class LocationIntegrationTests {
> ```

:100: Nice clean up moving this to a different file!


<!-- Sent from Reviewable.io -->

2021-03-02 00:07 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby, @gonzalonarbaiz, and @jkasten2)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateEmailSynchronizer.java, line 48 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263#-MUhTOdU9PuWHGElokgm:-MUkFadN1C8HSxTjzVsf:bdtysui) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/f4ae88a007d0b78d053250def7d843fd576dd592/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateEmailSynchronizer.java#L48)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This class has `logoutEmail()` and `logoutSMS()`, I would expect `logoutChannel()` instead. I haven't looked at your other PR so this might be addressed.
</blockquote></details>

I Will address this on the logout PR! thanks for pointing this out, I agree 100%
___
*[OneSignalSDK/unittest/src/test/java/com/test/onesignal/LocationIntegrationTests.java, line 86 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263#-MUhUkI_4TW8e3KqkkOa:-MUkFhjUCsf8JodKz3sS:bdeavht) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/f4ae88a007d0b78d053250def7d843fd576dd592/OneSignalSDK/unittest/src/test/java/com/test/onesignal/LocationIntegrationTests.java#L86)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

:100: Nice clean up moving this to a different file!
</blockquote></details>

:fire: 


<!-- Sent from Reviewable.io -->

2021-03-05 04:24 UTC, jkasten2 approved these changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby and @gonzalonarbaiz)



<!-- Sent from Reviewable.io -->

2021-03-11 08:17 UTC, jkasten2 approved these changes
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby and @gonzalonarbaiz)



<!-- Sent from Reviewable.io -->

2021-03-11 18:05 UTC, emawby approved these changes

2021-03-12 22:08 UTC, merged

2021-05-24 19:55 UTC, zsliu commented
Any update regarding this issue which caused app crash?

2021-05-25 00:00 UTC, zsliu commented
Is there any work around or patch the class to catch ClassCastException, or any configuration to disable TrackAmazonPurchase?

2021-05-26 00:21 UTC, jkasten2 commented
@zsliu Could you let us know the `react-native-iap` version you are using as well as the Devices and Android / FireOS version you are seeing the crash on?

A possible work around would be to use an older version of the Amazon IAP library.