WIP! added new method to get TZid.
OneSignal/OneSignal-Android-SDK pull request #1270
Opened 2021-01-29 19:50 UTC by gonzalonarbaiz

tests are missing and we have to validate with BE team the id to be used.

2021-02-01 17:02 UTC, jkasten2 requested changes
* Please add a unit test
* nit on extra import we don't need to include

2021-02-01 17:02 UTC, jkasten2 commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java
> +import android.text.format.Time;
This import is not used, we can remove.

2021-02-09 16:11 UTC, Jeasmine commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java
> +      ShadowOneSignalRestClient.lastUrl = null;
Why do you need this line?

2021-02-09 16:11 UTC, Jeasmine commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java
> +      JSONObject jsonObject = new JSONObject(ShadowOneSignalRestClient.lastPost.toString());
no need for a new JSONObject, ShadowOneSignalRestClient.lastPost is already a JSONObject

2021-02-09 16:11 UTC, Jeasmine commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java
> +      TimeZone.setDefault(TimeZone.getTimeZone("Europe/London"));
Can you put "Europe/London" in a variable and reuse it on assertEquals?

2021-02-09 20:08 UTC, Jeasmine commented on OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java
> +      JSONObject jsonObject = new JSONObject(ShadowOneSignalRestClient.lastPost.toString());
Did you check this comment?

2021-02-11 20:01 UTC, Jeasmine approved these changes

2021-02-12 02:44 UTC, gonzalonarbaiz reviewed
Done

2021-02-16 19:27 UTC, jkasten2 approved these changes

2021-02-16 23:05 UTC, merged