Fix notification disabled by channel being restored
OneSignal/OneSignal-Android-SDK pull request #1289
Opened 2021-03-12 20:02 UTC by Jeasmine

Fix notification disabled by channel being restored
* If the user disables notifications while the application is closed or in the background, then gets notifications, this notification won't display. If the user then enables notification channel previously disable, then open the application, notifications were being displayed because of restoring
* Save as dismissed a notification disable by channel

Fix notification received
* Mark as received all notification even if they are silent

2021-03-15 17:36 UTC, jkasten2 requested changes
This test is failing on CI that could be related
https://travis-ci.com/github/OneSignal/OneSignal-Android-SDK/builds/219967374#L3672-L3678
```
com.test.onesignal.GenerateNotificationRunner > shouldHandleBasicNotifications FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at com.test.onesignal.GenerateNotificationRunner.shouldHandleBasicNotifications(GenerateNotificationRunner.java:842)
```

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-:-MVqwzEcDd3N6s46ytig:b-8rc1u4)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-15 19:10 UTC, jkasten2 requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289)* status: all files reviewed, 5 unresolved discussions (waiting on @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java, line 331 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrGgQmEEQ8eG__3Vjs:-MVrGgQn0iQ1IXE4SWOp:b-og4dqm) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L331)):*
> ```Java
> 
>       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
>          return OneSignalNotificationManager.notificationChannelEnabled(currentContext, notification.getChannelId());
> ```

It would be better if we put this at the top of the method to early return. No point in it trying to display notification if the channel is off were it will never be shown.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java, line 331 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrHRQB82n_7yB6F8yu:-MVrHRQB82n_7yB6F8yv:bz65gi6) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L331)):*
> ```Java
> 
>       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
>          return OneSignalNotificationManager.notificationChannelEnabled(currentContext, notification.getChannelId());
> ```

It doesn't look like we are account for notifications being completely disabled either. This can be done in this PR or a follow up, just wanted to make sure we don't forget.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java, line 147 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrBZ6i74ivB4imJxBd:-MVrBZ6i74ivB4imJxBe:b9kx1ux) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L147)):*
> ```Java
>             } else {
>                 // Notification might end not displaying because the channel for that notification has notification disable
>                 notificationDisabledByChannel = !GenerateNotification.displayNotificationFromJsonPayload(notificationJob);
> ```

`notificationDisabledByChannel` seems overly specific, this code only needs to know if it was displayed or not.
Suggested name `notificationDisplayed`, that way we don't deal with the `!` here either.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java, line 181 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrFfKDEluKuEju5zeY:-MVrFfKDEluKuEju5zeZ:batjkq) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L181)):*
> ```Java
> 
>         String notificationId = notificationJob.getApiNotificationId();
>         OSReceiveReceiptController.getInstance().sendReceiveReceipt(notificationId);
> ```

We actually only want to send received receipts if it was displayed. It is really a confirmed display so we should keep this at the bottom where it was. Could also add comment so this is caught need time. Or even better a unit test.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalNotificationManager.java, line 169 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrHn_h8ul1AFpjb4iB:-MVrHn_h8ul1AFpjb4iC:bhola5z) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalNotificationManager.java#L169)):*
> ```Java
>     static boolean notificationChannelEnabled(Context context, String channelId) {
>         boolean isEnabled = true;
>         if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
> ```

nit, might be a bit easier to read as an early return. I'll let you decide though.


<!-- Sent from Reviewable.io -->

2021-03-15 23:09 UTC, Jeasmine reviewed
> shouldHandleBasicNotifications
This is still a flaky test :disappointed: 

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-:-MVs7kfL8PbAQdZImnJv:b-ehkw98)* status: all files reviewed, 4 unresolved discussions (waiting on @jkasten2)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java, line 331 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrGgQmEEQ8eG__3Vjs:-MVs8-_LCeruAshvqdCZ:bfjjj9f) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L331)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It would be better if we put this at the top of the method to early return. No point in it trying to display notification if the channel is off were it will never be shown.
</blockquote></details>

but the channel is being set on notification on different methods
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java, line 331 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrHRQB82n_7yB6F8yu:-MVs85OKAqwEodF9SAEI:b-q8ilnv) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L331)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It doesn't look like we are account for notifications being completely disabled either. This can be done in this PR or a follow up, just wanted to make sure we don't forget.
</blockquote></details>

gotcha
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java, line 147 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrBZ6i74ivB4imJxBd:-MVs8R8G-1h5bhnB-rqo:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L147)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`notificationDisabledByChannel` seems overly specific, this code only needs to know if it was displayed or not.
Suggested name `notificationDisplayed`, that way we don't deal with the `!` here either.
</blockquote></details>

Done.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java, line 181 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrFfKDEluKuEju5zeY:-MVs8VfMEcAAGkrw9F-D:b-q8ilnv) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L181)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

We actually only want to send received receipts if it was displayed. It is really a confirmed display so we should keep this at the bottom where it was. Could also add comment so this is caught need time. Or even better a unit test.
</blockquote></details>

gotcha


<!-- Sent from Reviewable.io -->

2021-03-16 17:50 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-:-MVw9HTr8IJ9chv78l_h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java, line 331 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289#-MVrGgQmEEQ8eG__3Vjs:-MVw7cvw5W5NR3FFjSUA:brr7kla) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/0527f7498d1128d9622df3ddefa8f2d72052de2a/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L331)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

but the channel is being set on notification on different methods
</blockquote></details>

Thinking about this again, I don't think we can move anyway. As then `applyNotificationExtender` would not fire if the user turned off the notification channel.
So the way you have it here is good.


<!-- Sent from Reviewable.io -->

2021-03-17 17:45 UTC, jkasten2 approved these changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-03-17 20:55 UTC, merged