Add null check for currentActivityName
OneSignal/OneSignal-Android-SDK pull request #1304
Opened 2021-04-05 23:54 UTC by Jeasmine

* currentActivityName under WebViewManager for IAMs, might end being null
* Add log to know in which case might this field end null

2021-04-06 18:20 UTC, jkasten2 requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @emawby and @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 328 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1304#-MXcPEcV64QZa0YZsqwy:-MXcPEcV64QZa0YZsqwz:bam7170) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/384673bfda3d00367cf061e84b61afaaff48bb15/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L328)):*
> ```Java
>                 "currentActivityName: " + currentActivityName + "\nactivity: " + this.activity + "\nmessageView: " + messageView);
> 
>         if (messageView != null && currentActivityName != null && currentActivityName.equals(activity.getLocalClassName()))
> ```

I believe instead of adding `currentActivityName != null` we can instead do `activity.getLocalClassName().equals(currentActivityName)` to simplify this.


<!-- Sent from Reviewable.io -->

2021-04-08 18:17 UTC, emawby approved these changes
approved pending Josh's simplification!

2021-04-13 17:22 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1304)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 328 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1304#-MXcPEcV64QZa0YZsqwy:-MYBFRMo9-gSNqB7Migq:b6zrrk4) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/384673bfda3d00367cf061e84b61afaaff48bb15/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L328)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I believe instead of adding `currentActivityName != null` we can instead do `activity.getLocalClassName().equals(currentActivityName)` to simplify this.
</blockquote></details>

Good catch!


<!-- Sent from Reviewable.io -->

2021-04-13 18:23 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-04-13 18:51 UTC, merged