Feature app-defined language implementation
OneSignal/OneSignal-Android-SDK pull request #1334
Opened 2021-05-18 22:43 UTC by tanaynigam

# Description

## Line Summary
Add feature app-defined language implementation. A user can define their own language setting to be used by OneSignal-SDK

# Details
* Add `LanguageContext`, `LanguageProviderAppDefined` and `LanguageProviderDevice` class
* `LanguageContext` uses strategy pattern to retrieve either app-defined or device language
* `LanguageProviderAppDefined` retrieves app-defined language
* `LanguageProviderDevice` retrieves device language
* Add `LanguageProvider` interface that defines method getLanguage
* Add network call to `OneSignal.setLanguage` method that saves app-defined language to `OneSignal.preferences`
* Remove `OSUtils.getCorrectedLanguage` method
* Replace `LanguageProviderDevice.getLanguage` method with implementation from `OSUtils.getCorrectedLanguage`
* Add `OSSharedPreferences` dependency injection to `LanguageContext` and `LanguageProviderAppDefined` constructors
* Inject `OneSignal.preferences` into `LanguageContext` initialization
* Add `LanguageContext` dependency injection in `OSInAppMessageController`, `OSInAppMessageControllerFactory` and `OSInAppMessageDummyController` constructors
* Add `LanguageContext.getLanguage` to `OSInAppMessageController.variantIdForMessage`
* Add singleton pattern to `LanguageContext` class
* Add `getLanguage` method to `NotificationChannelManager.createChannel` using `LanguageContext` instance

# Test
* Add `MainOneSignalClassRunner` `testSetLanguageOnPlayerCreate`, `testSetLanguagePUTRequest`, `testSetLanguageOnSession` unit tests
* Test device using button click to call `OneSignal.setLanguage` to set it to language different from language defined by the device. OneSignal app dashboard reflects the language set using `OneSignal.setLanguage`

2021-05-19 06:03 UTC, jkasten2 requested changes
Left a few comments in the code with some nits line-by-line:

Also a number of tests are failing due to `null` errors:
1. Missing LanguageContext for IAMs in tests. https://travis-ci.com/github/OneSignal/OneSignal-Android-SDK/builds/226256046#L3605-L3611
2. Some notification channel tests failing. https://travis-ci.com/github/OneSignal/OneSignal-Android-SDK/builds/226256046#L1845-L1850

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-:-Ma2CZDZE-AD4t-0174E:bozx86o)* status: all files reviewed, 4 unresolved discussions (waiting on @emawby and @tanaynigam)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1694 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-Ma2BGuoBrivHS6999Q-:-Ma2BGuoBrivHS6999Q0:b-rlod99) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c3e2ea5bb4ef4ed094581ce167672a27e030d031/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1694)):*
> ```Java
>          OneSignalStateSynchronizer.updateDeviceInfo(deviceInfo);
>       } catch (JSONException exception) {
>          String operation = language.equals("") ? "remove" : "set";
> ```

We can omit this `operation` logic as you can only set a language, not remove it.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageContext.java, line 19 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-Ma2Ba-B9B9DjSh1WPFz:-Ma2Ba-C1xCZPxYes3UI:b5c564p) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c3e2ea5bb4ef4ed094581ce167672a27e030d031/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageContext.java#L19)):*
> ```Java
>     public LanguageContext(OSSharedPreferences preferences) {
>         instance = this;
>         if ( preferences.getString(
> ```

nit, remove extra space before `preferences`.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderAppDefined.java, line 4 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-Ma2BrRn3YNUuJea_ozl:-Ma2BrRo0kgiM_gcM2-M:b-4h1o9f) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c3e2ea5bb4ef4ed094581ce167672a27e030d031/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderAppDefined.java#L4)):*
> ```Java
> import com.onesignal.OSSharedPreferences;
> 
> public class LanguageProviderAppDefined implements LanguageProvider{
> ```

nit, should be space after `LanguageProvider`
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderDevice.java, line 5 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-Ma2C00j7qoh-P9OSLxg:-Ma2C00k2AIzysjwzD1M:b-4h1o9f) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c3e2ea5bb4ef4ed094581ce167672a27e030d031/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderDevice.java#L5)):*
> ```Java
> import java.util.Locale;
> 
> public class LanguageProviderDevice implements LanguageProvider{
> ```

nit, should be space after `LanguageProvider`


<!-- Sent from Reviewable.io -->

2021-05-21 04:30 UTC, jkasten2 approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby)



<!-- Sent from Reviewable.io -->

2021-05-21 17:10 UTC, emawby approved these changes

2021-05-21 17:25 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334)* status: all files reviewed, 4 unresolved discussions (waiting on @tanaynigam)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1677 at r2](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-MaEwCJDENkAjEHjYGpU:-MaEwCJDENkAjEHjYGpV:bqj3qa3) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/dad265e32d920cbd72d9dfdbed09c5bf968799dc/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1677)):*
> ```Java
>       }
> 
>       if (shouldLogUserPrivacyConsentErrorMessageForMethodName("setLanguage()"))
> ```

Instead of "setLanguage()" string, what about using the constant OSTaskRemoteController.SET_Language?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageContext.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-MaEweltDoj8zs7pYzT1:-MaEwelu383mcq5C56hO:bb4mmwn) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/dad265e32d920cbd72d9dfdbed09c5bf968799dc/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageContext.java#L19)):*
> ```Java
>     public LanguageContext(OSSharedPreferences preferences) {
>         instance = this;
>         if (preferences.getString(
> ```

For easier readability, would you mind putting the if condition inside a variable?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderAppDefined.java, line 21 at r2](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-MaEx3gp52MM1xmsXxKt:-MaEx3gp52MM1xmsXxKu:bndq8me) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/dad265e32d920cbd72d9dfdbed09c5bf968799dc/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderAppDefined.java#L21)):*
> ```Java
>     public String getLanguage() {
>         return preferences.getString(
>                 preferences.getPreferencesName(), PREFS_OS_LANGUAGE, "en");
> ```

Code styling comment, would you mind moving the "en" string to a class constant string?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderDevice.java, line 10 at r2](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334#-MaExFkX0-ie0olFrlBW:-MaExFkX0-ie0olFrlBX:b-u5gri0) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/dad265e32d920cbd72d9dfdbed09c5bf968799dc/OneSignalSDK/onesignal/src/main/java/com/onesignal/language/LanguageProviderDevice.java#L10)):*
> ```Java
> 
>         // https://github.com/OneSignal/OneSignal-Android-SDK/issues/64
>         if (lang.equals("iw"))
> ```

would it make sense to have enums instead of strings?


<!-- Sent from Reviewable.io -->

2021-05-25 21:38 UTC, jkasten2 approved these changes
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1334)* status: all files reviewed, 4 unresolved discussions (waiting on @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-05-25 22:17 UTC, Jeasmine approved these changes

2021-05-25 22:20 UTC, merged