using latest HMS push version
OneSignal/OneSignal-Android-SDK pull request #1378
Opened 2021-07-09 16:45 UTC by emawby

This is changing  in response to the Implicit PendingIntent issue.

2021-07-09 17:57 UTC, jkasten2 requested changes
Tests stalled on `NotificationOpenedActivityHMSIntegrationTestsRunner`, possibly need to update a shadow.
https://app.travis-ci.com/github/OneSignal/OneSignal-Android-SDK/builds/232312479#L2176-L2182

Rerunning again though to confirm it isn't a flaky test.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1378#-:-MeBPMsqEG3V5mqsLyKm:b-vxodbl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-07-12 22:03 UTC, jkasten2 approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-07-12 22:03 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1378#-:-MeRjffGAyX9qETMqL0y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-07-13 17:00 UTC, Jeasmine approved these changes

2021-07-13 18:33 UTC, merged