Match and fix any external id that has escaped forward slashes
OneSignal/OneSignal-Android-SDK pull request #1478
Opened 2021-11-03 15:27 UTC by adamschlesinger

Fix for https://app.asana.com/0/1193807006058450/1201230887422941/f which explicitly only checks outbound external user ids. 

This will NOT prevent the client from saving the EID with escaped slashes. This is why there is no `if (matched != currentEID)` check. We cannot rely on the current EID on the client to be unescaped.

2021-11-04 21:43 UTC, jkasten2 requested changes
Cod 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-:-MngofrbASf2XIGBDlHb:bb6tzrh)* status: all files reviewed, 2 unresolved discussions (waiting on @adamschlesinger, @emawby, and @jmadler)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java, line 164 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-MngrpsP0rXzCJnhStbk:-MngrpsP0rXzCJnhStbl:b-i6puri) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/a72bb20cf3e660c7a37529d7493aa6ae2eddf16c/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L164)):*
> ```Java
>             String strJsonBody = jsonBody.toString();
> 
>             Pattern eidPattern = Pattern.compile("(?<=\"external_user_id\":\").*\\\\/.*?(?=\",|\"\\})");
> ```

Looks like you have an extra `\` on the or operator when looking for `}`. I believe the full regex should be
```regex
(?<=\"external_user_id\":\").*\\\\/.*?(?=\",|\"\})
```

Tested with the following to confirm:
https://regex101.com/r/yAlOnr/1/
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java, line 167 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-Mngslvq5AVeORUpzE9K:-Mngslvq5AVeORUpzE9L:b-dty7uh) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/a72bb20cf3e660c7a37529d7493aa6ae2eddf16c/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L167)):*
> ```Java
>             Matcher eidMatcher = eidPattern.matcher(strJsonBody);
> 
>             if (eidMatcher.find()) {
> ```

We be nice to split this code into it's own descriptive method so we don't have to add the implementation details don't have to live in the `startHTTPConnection` method itself.


<!-- Sent from Reviewable.io -->

2021-11-05 02:30 UTC, adamschlesinger reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478)* status: all files reviewed, 2 unresolved discussions (waiting on @adamschlesinger, @emawby, @jkasten2, and @jmadler)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java, line 164 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-MngrpsP0rXzCJnhStbk:-MnhvPnmEvtlPIjkhJVO:b-g7izbx) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/a72bb20cf3e660c7a37529d7493aa6ae2eddf16c/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L164)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Looks like you have an extra `\` on the or operator when looking for `}`. I believe the full regex should be
```regex
(?<=\"external_user_id\":\").*\\\\/.*?(?=\",|\"\})
```

Tested with the following to confirm:
https://regex101.com/r/yAlOnr/1/
</blockquote></details>

You need to escape the escape for Java.


<!-- Sent from Reviewable.io -->

2021-11-05 21:58 UTC, jkasten2 reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger, @emawby, and @jmadler)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java, line 164 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-MngrpsP0rXzCJnhStbk:-Mnm5m3jEPcMK_utggiN:b38524o) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/a72bb20cf3e660c7a37529d7493aa6ae2eddf16c/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L164)):*
<details><summary><i>Previously, adamschlesinger (Adam Schlesinger) wrote…</i></summary><blockquote>

You need to escape the escape for Java.
</blockquote></details>

ah you are right, tested it in Java and you need to have exactly`\\}` for it to work.


<!-- Sent from Reviewable.io -->

2021-11-05 22:01 UTC, jkasten2 approved these changes
1 comment left, recommended code clean up but not required.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1478#-:-Mnm6Qn58JMm1ucvto-f:bt4edxv)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger, @emawby, and @jmadler)



<!-- Sent from Reviewable.io -->

2021-11-05 22:52 UTC, merged