Fix Permission observer not being called
OneSignal/OneSignal-Android-SDK pull request #1521
Opened 2022-01-21 23:46 UTC by Jeasmine

# Description
## One Line Summary
Permission observer was not being called when swapping fast between application and settings apps

## Details

### Motivation
PermissionObserver needs to be called for all scenarios when the user disables/enables the notification

### OPTIONAL - Other
* When the user swaps from the app to the setting and enables/disable notification fast enough no avoid onLostFocus runnable, the permission observer was not being fired
* Add new lifecycle event tracking, onStart, and onStop
* Check permission under on Start

## Manual testing
Followed steps given under https://github.com/OneSignal/OneSignal-Android-SDK/issues/1392

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-01-24 18:02 UTC, emawby approved these changes

2022-01-27 08:18 UTC, jkasten2 requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1521)* status: all files reviewed, 2 unresolved discussions (waiting on @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1380 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1521#-MuPauts7siy-fQM_XKZ:-MuPauts7siy-fQM_XK_:b451fwm) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/ba6d2f7287260b2fbb0a500c6e72ce1fca7f4ad2/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1380)):*
> ```Java
>    static void onAppStartFocusLogic() {
>       // Make sure without privacy consent, onAppStopFocusLogic returns early
>       if (shouldLogUserPrivacyConsentErrorMessageForMethodName("onAppStartFocusLogic"))
> ```

I think we should remove this, otherwise it will skip the refresh below and the internal state of the SDK will be wrong when the user accepts privacy consent. We have other code in place from preventing the network request. 
___
*[OneSignalSDK/unittest/src/test/java/com/onesignal/ShadowFocusHandler.kt, line 44 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1521#-MuPaFka0gfDsS9IMA_l:-MuPaFka0gfDsS9IMA_m:b-95n4tv) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/ba6d2f7287260b2fbb0a500c6e72ce1fca7f4ad2/OneSignalSDK/unittest/src/test/java/com/onesignal/ShadowFocusHandler.kt#L44)):*
> ```Kotlin
> 
>     @RealObject
>     private val realFocusHandler: OSFocusHandler? = null
> ```

Seems like this isn't used, please delete if not needed.


<!-- Sent from Reviewable.io -->

2022-01-27 21:49 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1521#-:-MuSVuT-0Dpj61Ji7Ux4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2022-01-27 22:09 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1521#-:-MuS_NHj6ROw43NG7htf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2022-01-27 22:23 UTC, merged