WIP - Fix HMS Activity trampolining
OneSignal/OneSignal-Android-SDK pull request #1533
Opened 2022-02-10 16:41 UTC by Jeasmine

* HMS notification with Message type "Message" won't trigger activity trampolining logic
* Start application from NotificationOpenedActivityHMS

# READ AND DELETE THIS SECTION BEFORE SUBMITTING PR
* **Fill out each _REQUIRED_ section**
* **Fill out _OPTIONAL_ sections, remove section if it doesn't apply to your PR**
* **Read and fill out each of the checklists below**
* **Remove this section after reading**

# Description
## One Line Summary
**REQUIRED** - Very short description that summaries the changes in this PR.

## Details

### Motivation
**REQUIRED -** Why is this code change being made? Or what is the goal of this PR? Examples: Fixes a specific bug, provides additional logging to debug future issues, feature to allow X.

### Scope
**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-02-10 22:10 UTC, Jeasmine commented
@jkasten2 will love your point of view in this PR 🙏

2022-02-11 22:27 UTC, jkasten2 requested changes
@jeasmine Thanks for diving in and fixing the issue! Just some things to clean up in the PR and we can get it merged in.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-:-MvetM8u2MDs5a-aq6Pu:b-ypvs31)* status: all files reviewed, 4 unresolved discussions (waiting on @Jeasmine)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2339 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesR2rCFgRhOdmJVv1:-MvesR2rCFgRhOdmJVv2:b-1eunqa) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2339)):*
> ```Java
>     * Method called when opening a notification
>     */
>    static void handleNotificationOpen(final Activity context, final JSONArray data, final boolean fromHMSMessage, @Nullable final String notificationId) {
> ```

Instead of naming this `fromHMSMessage` we should come up with a boolean name that is more generic, to separate concerns. Something like `startLauncherActivity`?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2368 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvespBhBL5I3O_C3TqH:-MvespBi5iAfwT3uWKqE:be1v2oc) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2368)):*
> ```Java
>          applicationOpenedByNotification(notificationId);
> 
>          // HMS notification with Message Type being Message won't trigger Activity reverse trampolining logic
> ```

This comment would be better fit if it was added to `notificationPayloadProcessorHMS.java` instead.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2372 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesVpbCuZBUOINZ5z7:-MvesVpbCuZBUOINZ5z8:b-8bcy4k) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2372)):*
> ```Java
>          // Last EMUI (12 to the date) is based on Android 10, so no
>          // Activity trampolining restriction exist for HMS devices
>          if (OSUtils.isHuaweiDeviceType() && fromHMSMessage) {
> ```

Checking `OSUtils.isHuaweiDeviceType()` is redundant, we can remove it.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2381 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesyhPCtOTWEpXUoi5:-MvesyhPCtOTWEpXUoi6:be9sx90) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2381)):*
> ```Java
>    }
> 
>    // This opens the app in the same way an Android home screen launcher does.
> ```

Let's add a comment that reverse activity traplining is used for most notifications, this  method is only used if the push provider does support it.


<!-- Sent from Reviewable.io -->

2022-02-15 16:31 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @emawby and @jkasten2)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2339 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesR2rCFgRhOdmJVv1:-MvyBte1-yEhjcBRJa7s:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2339)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Instead of naming this `fromHMSMessage` we should come up with a boolean name that is more generic, to separate concerns. Something like `startLauncherActivity`?
</blockquote></details>

Done.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2368 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvespBhBL5I3O_C3TqH:-MvyBxni03j-t517Iw9m:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2368)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This comment would be better fit if it was added to `notificationPayloadProcessorHMS.java` instead.
</blockquote></details>

Done.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2372 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesVpbCuZBUOINZ5z7:-MvyBxYACoCHXvx7AngW:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2372)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Checking `OSUtils.isHuaweiDeviceType()` is redundant, we can remove it.
</blockquote></details>

Done.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2381 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesyhPCtOTWEpXUoi5:-MvyC00s2DJUQLeVUVxE:bdiogf1) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2381)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Let's add a comment that reverse activity traplining is used for most notifications, this  method is only used if the push provider does support it.
</blockquote></details>

Nice catch


<!-- Sent from Reviewable.io -->

2022-02-15 16:31 UTC, Jeasmine commented
> @Jeasmine Thanks for diving in and fixing the issue! Just some things to clean up in the PR and we can get it merged in.
> 
> > Reviewed 4 of 4 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-:-MvetM8u2MDs5a-aq6Pu:b-ypvs31)_ status: all files reviewed, 4 unresolved discussions (waiting on @Jeasmine)
> 
> _[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2339 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesR2rCFgRhOdmJVv1:-MvesR2rCFgRhOdmJVv2:b-1eunqa) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2339)):_
> 
> > ```java
> >     * Method called when opening a notification
> >     */
> >    static void handleNotificationOpen(final Activity context, final JSONArray data, final boolean fromHMSMessage, @Nullable final String notificationId) {
> > ```
> 
> Instead of naming this `fromHMSMessage` we should come up with a boolean name that is more generic, to separate concerns. Something like `startLauncherActivity`?
> 
> _[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2368 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvespBhBL5I3O_C3TqH:-MvespBi5iAfwT3uWKqE:be1v2oc) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2368)):_
> 
> > ```java
> >          applicationOpenedByNotification(notificationId);
> > 
> >          // HMS notification with Message Type being Message won't trigger Activity reverse trampolining logic
> > ```
> 
> This comment would be better fit if it was added to `notificationPayloadProcessorHMS.java` instead.
> 
> _[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2372 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesVpbCuZBUOINZ5z7:-MvesVpbCuZBUOINZ5z8:b-8bcy4k) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2372)):_
> 
> > ```java
> >          // Last EMUI (12 to the date) is based on Android 10, so no
> >          // Activity trampolining restriction exist for HMS devices
> >          if (OSUtils.isHuaweiDeviceType() && fromHMSMessage) {
> > ```
> 
> Checking `OSUtils.isHuaweiDeviceType()` is redundant, we can remove it.
> 
> _[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 2381 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-MvesyhPCtOTWEpXUoi5:-MvesyhPCtOTWEpXUoi6:be9sx90) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/d2fc7ca83d9ac223c4684c9b2aab1a0077eb44b4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L2381)):_
> 
> > ```java
> >    }
> > 
> >    // This opens the app in the same way an Android home screen launcher does.
> > ```
> 
> Let's add a comment that reverse activity traplining is used for most notifications, this method is only used if the push provider does support it.

Thanks for the review!

2022-02-15 19:19 UTC, emawby approved these changes

2022-02-15 21:56 UTC, nan-li approved these changes

2022-02-16 04:32 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1533#-:-Mw-nPfM5rd8EWx7-5hS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)



<!-- Sent from Reviewable.io -->

2022-02-16 20:04 UTC, merged

2022-03-04 00:15 UTC, jkasten2 commented
@peter-rosendahl Just wanted to call out to you this should fix the issue in the https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494#issuecomment-1017613894 you left. It is now available in the 4.7.0 release:
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.0

2022-03-10 12:32 UTC, dkoeltringer commented
@jkasten2 I have a similar or the same issue as @peter-rosendahl with the OneSignal SDK for Android. I hoped it is fixed now with the 4.7.0 release, but the issue is still present on my Huawei device. The notification is present, but when clicking on it, the app is not opened.
Can you have a look on this? If you need additional information, I am glad to help!

2022-03-10 18:23 UTC, jkasten2 commented
@dkoeltringer Thanks for reporting. Is the issue happening with "message" and / or "data" Huawei HMS notification types?
By default OneSignal uses HMS "message" type but you can change this via the REST API by adding `huawei_msg_type` or setting it under the notification settings on the dashboard before seeing:
 * https://documentation.onesignal.com/reference/create-notification#attachments
Note that "data" type will still display a notification as long as you include a notification body.

The different is important as they work much differently from another.

## Questions
1. Does the issue happen with "message" and / or "data" Huawei HMS notification types?
2. Does the state of your app matter? App backgrounded vs closed swiped away.
3. What version of EMUI and Android do you see the issue on?
4. Provide a full system logcat with no filtering so we can see the system events to debug.

2022-03-11 06:54 UTC, dkoeltringer commented
@jkasten2 Thank you for your quick reply!
One maybe important thing, I have missed in my last post: The issue happens only if there is a launch url added. Without the launch url the app is started without problem, but only the main activity, because the launch url is missing.

Here the answers for your questions:
1. We used HMS notification type "message". After trying "data" everything **worked** without problem. So I think this is the fix we have searched for.
2. Does not matter.
3. EMUI 10.1.0, Android 10
4. Do you still need the logcat for analyzing the issue, or is this not needed anymore, because the issue has resolved with the "data" notification type?

Thank you very much for your help!