Fix NPE for `outcomeEventsController` during initialization
OneSignal/OneSignal-Android-SDK pull request #1539
Opened 2022-03-03 16:52 UTC by nan-li

# Description
## One Line Summary
Lazily initialize and access the `OneSignal.outcomeEventsController`, adding a null check when invoking its methods that wasn't checked before, as it may not have been initialized yet in the critical initialization step of `setupContextListeners()`.

## Details

### Motivation
This is a speculative fix for a non-reproducible `NullPointerException` of `outcomeEventsController.sendSavedOutcomes()` during initialization, as reported by users in production [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1374) and [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1514).

### Context
During initialization, `initWithContext()` and `setAppId()` run. The first method also initializes the `outcomeEventsController` in the method `setupContextListeners()` [see code](https://github.com/OneSignal/OneSignal-Android-SDK/blob/10867586a325eaf9e69292e5d3e288083768ce8a/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L874).

After the appContext and appId are set by the above methods, the `init()` method runs, which calls `OSOutcomeEventsController.sendSavedOutcomes()` [towards the method's end](https://github.com/OneSignal/OneSignal-Android-SDK/blob/10867586a325eaf9e69292e5d3e288083768ce8a/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L837). 

It **may** be that in some cases, the `init()` method is called before `initWithContext()` is fully complete, resulting in a null `outcomeEventsController` instance that `init()` relies on.

One GitHub reporter speculated it is due to adding `setLanguage` functionality in `4.4.0`, and there are now more calls to `initWithContext` added in `4.4.1` for more FCM entry points. 

It is possible that multiple threads are initializing and one hangs after setting the `appContext` but hasn't finished `setupContextListeners`.

This is ultimately speculative and it may be some other reason that `outcomeEventsController` is `null`.

### Implementation Details
When we want to access `OneSignal.outcomeEventsController`, use lazy initialization and singleton pattern to access and create it via `getOutcomeEventsController()`. Use synchronization when creating the object.

There are some methods where `outcomeEventsController` is called such as in `sendUniqueOutcome()` where there is already a `null` check and the method returns if `outcomeEventsController == null`. In these methods I didn’t make any changes as it already had its own null check logic.

### Scope
This affects OneSignal initialization.

### Potential Problems
If the root issue is in fact that `setupContextListeners()` isn't completed before `init()` runs, it may be possible that `languageContext` isn't initialized either. In this case, while we move past the NPE for `outcomeEventsController`, we may encounter a NPE for `languageContext` next, such as in `registerUserTask()` or when it is passed as an argument to `getInAppMessageController()`.

However, that may be far enough down the line that it won't pose a problem.

# Testing
## Unit testing
Added unit test to simulate `setupContextListeners()` not completing:

- Add unit test `initWithContext_setupContextListenersNotCompleted_doesNotProduceNPE` to reproduce the NPE of `outcomeEventsController` in `init()`.

- Shadow the `OneSignal.setupContextListeners()` method to simulate it not completing (thus not initializing the `outcomeEventsController`).

- However, the `languageContext` initialization is needed or else it leads to a subsequent NPE for this property in `registerUserTask()`.

- Change access of `languageContext` in OneSignal.java from private to package-private so it can be accessed in unit tests.

- All other unit tests pass

## Manual testing
App built with Android Studio 2020.3.1 with the OneSignal example app on a Pixel 5 with API 30.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, but is insufficient as this error is not reproducible.

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1539)

2022-03-22 22:42 UTC, jkasten2 requested changes
Logic changes look good, have a concern about the shadow changes though and it effecting other tests.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1539#-:-MynmvidBM9oj-mIUvY_:bi5bxwl)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine and @nan-li)

___
*[OneSignalSDK/unittest/src/test/java/com/onesignal/ShadowOneSignal.java, line 30 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1539#-MynlPTBBhgOIPcgYE68:-MynlPTBBhgOIPcgYE69:b4tzwf2) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/2cfe353184141cab6963d94b9848a412e8ef1413/OneSignalSDK/unittest/src/test/java/com/onesignal/ShadowOneSignal.java#L30)):*
> ```Java
>     */
>    @Implementation
>    public static void setupContextListeners(boolean wasAppContextNull) {
> ```

There are a number of tests using this shadow, this method changes the behavior quite a bit. Can we confirm if this change is needed at all?

If it is could we do one of the following?:
1. By default call the original logic, we could add an if statement to check a flag and only set it in the test that needs this.
2. Create a different class that shadows the OneSignal class and only use it in the test you need.


<!-- Sent from Reviewable.io -->

2022-03-23 18:50 UTC, nan-li commented
> There are a number of tests using this shadow, this method changes the behavior quite a bit. Can we confirm if this change is needed at all?
>
> If it is could we do one of the following?:
> 1. By default call the original logic, we could add an if statement to check a flag and only set it in the test that needs this.
> 2. Create a different class that shadows the OneSignal class and only use it in the test you need.

Good catch, I've created a new shadow class `ShadowOneSignalWithMockSetupContextListeners` just for the added unit test that has the modified `setupContextListeners()` method.

2022-03-23 19:31 UTC, jkasten2 approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1539)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby and @Jeasmine)



<!-- Sent from Reviewable.io -->

2022-03-23 19:56 UTC, nan-li commented
`shouldSetExpireTimeCorrectlyWhenMissingFromPayload` has been regularly failing here, off by 1 second. I've re-ran the build a few times in the past 1-2 days.

Running the unit tests locally twice, they all pass.

2022-03-31 17:42 UTC, merged