[Fix] Add duplicates check when loading operation models from cache
OneSignal/OneSignal-Android-SDK pull request #2099
Opened 2024-05-29 03:59 UTC by nan-li

# Description
## One Line Summary
Add duplicates check when loading operation models from cache.

## Details
* This check is added to remedy the Operation Model Store adding duplicate operations when the same ones that were previously added to the store and persisted, are re-read from cache.
* A similar duplicates check already exists in the Operation Repo when operations are enqueued onto it.
* Though the duplicate would not get enqueued to the Operation Repo, the duplicate was still persisted. When the operations are successful, only one of the duplicates will be removed from cache as the removal logic utilizes a `firstOrNull` search for the operation. Then, on the next cold start, the remaining operation will load from cache and become enqueued to the OperationRepo.

Bug introduced in v5.1.12 with the Operations loading changes to prevent ANRs.

### Motivation
Bug fix

### Scope
Prevents duplicated operations on the next cold start

# Testing
## Unit testing
None

## Manual testing
Android emulator on API 33

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2024-05-29 14:35 UTC, jinliu9508 commented
Code looks good and the test works!

Should we consider removing the duplicates since they are most likely unnecessary in the event that a duplicate scenario occurs?

2024-05-29 16:44 UTC, jinliu9508 commented
> > Should we consider removing the duplicates since they are most likely unnecessary in the event that a duplicate scenario occurs?
> 
> Can you explain what you mean? This PR prevents a duplicate operation from being added. Are you talking about the model store's [remove method](https://github.com/OneSignal/OneSignal-Android-SDK/blob/d9c8110263fa94d6e0409ddcc03b9cd9c59ee95b/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/ModelStore.kt#L84)?

Sure. If the user already has duplicate operations in the cache from migrating from 5.1.12, the saved operations will not be added to the model store but will remain in the cache. I am thinking we can add an extra step to remove the duplicates if they are detected and ensure a cleaner migration.

2024-05-29 17:44 UTC, nan-li commented
> Sure. If the user already has duplicate operations in the cache from migrating from 5.1.12, the saved operations will not be added to the model store but will remain in the cache. I am thinking we can add an extra step to remove the duplicates if they are detected and ensure a cleaner migration.

I see, I don't think another check or removal from cache is necessary because of the following reasons:
- Anytime `persist()` is called, the cache will be overwritten with the current models. And the current models we now prevent adding duplicates to, so models will not have duplicates anymore.
- In normal circumstances, you can't tell when an operation is actually a duplicate from the past. From the example above, 2 identical `login-user` operations were added to the operation model store and cached. The first one should be sent very quickly and removed once the request is successful, leaving one more operation in the store and cache.
- On the next cold start, that operation will be read from the cache and put in the store. This is actually a duplicate and we would not know.

2024-05-29 18:56 UTC, jkasten2 requested changes
@nan-li Nice catch here! Didn't think about the case where `OperationRepo._operationModelStore` would still contain the duplicate.

Another question comes to mind now, do we need to keep the duplicate check in `internalEnqueue` as well? I am thinking yes, since we still need to ensure it doesn't get put into `OperationRepo.queue`, where it would be processed during the currently runtime.
* This problem however does point to a duplicate state complexity we have in our system. Something that would be nice to clean up in the future, if possible.

Lastly, could we add a test before merging this in?

2024-05-30 14:18 UTC, jinliu9508 approved these changes

2024-05-30 19:45 UTC, jkasten2 commented
Thinking about this again the root of the problem is `ModelStore.load` doesn't do what you would think it does. It should take exactly what is on disk and use that for it state (AKA model list), instead it is appending it which I think is the root of the problem.

2024-05-30 20:23 UTC, nan-li commented
> Another question comes to mind now, do we need to keep the duplicate check in `internalEnqueue` as well? 
Yes we still need the check in the Operation Repo. The operations are already enqueued to the Op Repo before `load()` is called. 

> Thinking about this again the root of the problem is ModelStore.load doesn't do what you would think it does. It should take exactly what is on disk and use that for it state (AKA model list), instead it is appending it which I think is the root of the problem.

This is a good point, I agree. I checked that the cache should always be updated and correct, so it is safe to do a full replacement. I updated the PR.

2024-05-30 20:26 UTC, jkasten2 approved these changes
LGTM! Much simpler logic now!

2024-05-30 21:46 UTC, nan-li commented
Thinking again about the model store reading from cache, I realized that it will almost always lose old cached operations...

1. There are some cached operations
2. If there is a onesignal ID, on next cold start, `refresh-user` enqueues and persists. This will overwrite the cache.
3. Then `load` is called, loading only the `refresh-user` operation.

2024-05-30 23:34 UTC, jkasten2 commented
I see, so this isn't just a problem with `ModelStore.load()`. We need to do something with OperationRepo so it doesn't overwrite the local data.

2024-05-31 19:26 UTC, nan-li commented
Testing again, I think the `refresh-user` operation comes after Operation Repo loads operations, so the situations of overwriting cache are rare. 

I have only been able to reproduce with the creation of the initial anonymous user, as those operations enqueue really early in `initWithContext`.
Or, by having a delay to the coroutine that loads operations.

2024-06-04 20:28 UTC, jkasten2 requested changes

2024-06-04 20:28 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/ModelStore.kt
> +        val shouldRePersist = models.isNotEmpty()
This should be in the `synchronized(models) {}` below to prevent race conditions and concurrent modification expectations.

2024-06-05 17:23 UTC, jkasten2 approved these changes

2024-06-06 18:32 UTC, merged