Make use of `ryw_delay` to minimize retries on IAM fetch
OneSignal/OneSignal-Android-SDK pull request #2207
Opened 2024-10-24 21:30 UTC by rgomezp

# Description
## One Line Summary
Encapsulate `rywToken` and `rywDelay` into a `RywData` class and update usage throughout the codebase including delaying IAM fetch by the specified delay.

## Details

### Motivation
This update introduces the **RywData** class to group `rywToken` and `rywDelay` into a single data object. This ensures both values are handled together, allowing for accurate delay management based on the most recent `rywToken`.

### Scope
- **Encapsulated `rywToken` and `rywDelay`** into the new `RywData` class to centralize their usage.  
- **Updated method signatures**: All previous usages of `String` (`rywToken`) are replaced with the new `RywData` object.  
  - Renamed `setRywToken` method to **`setRywData`** to reflect this change.
- **IAM fetch logic adjusted**: The delay for IAM fetch now leverages the `rywDelay` value from `RywData`. A fallback mechanism ensures minimal retries to the backend.
- **Renamed methods for clarity**, ensuring method names convey when a value is expected to be returned.

# Testing
## Unit testing
Tests were updated & passed.

## Manual testing
Tested accurate segment membership calculation & display of IAMs. e.g:
1. Create two IAMs targeting segments with version 1, & another targeting version 2 of the app
2. Set the IAMs to display every time conditions are met
3. Switch back & forth between versions in the example app
4. See that you get the correct IAM

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [x] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2024-10-28 22:06 UTC, jkasten2 requested changes

2024-10-29 19:43 UTC, rgomezp commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/consistency/IamFetchReadyCondition.kt
> -        return listOfNotNull(tokenMap[IamFetchRywTokenKey.USER], tokenMap[IamFetchRywTokenKey.SUBSCRIPTION]).maxOrNull()
maxOrNull compares lexicographically & we're generating the token already with a buffer so they're all equal length

2024-10-30 21:41 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/consistency/IamFetchReadyCondition.kt
> -        return listOfNotNull(tokenMap[IamFetchRywTokenKey.USER], tokenMap[IamFetchRywTokenKey.SUBSCRIPTION]).maxOrNull()
We discussed and this safe due the fact the length never changes, these rules are followed:
* "1" - encoding version
* "0000..." - zero buffer
* "54442713589" - offset value

2024-10-30 21:55 UTC, jkasten2 requested changes

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/SubscriptionBackendService.kt
> +        fun JSONObject.safeString(key: String): String? = if (this.has(key)) this.getString(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeString` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/SubscriptionBackendService.kt
> +        fun JSONObject.safeLong(key: String): Long? = if (this.has(key)) this.getLong(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeLong` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/SubscriptionBackendService.kt
> +        fun JSONObject.safeString(key: String): String? = if (this.has(key)) this.getString(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeString` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/SubscriptionBackendService.kt
> +        fun JSONObject.safeLong(key: String): Long? = if (this.has(key)) this.getLong(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeLong` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/UserBackendService.kt
> +        fun JSONObject.safeString(key: String): String? = if (this.has(key)) this.getString(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeString` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/backend/impl/UserBackendService.kt
> +        fun JSONObject.safeLong(key: String): Long? = if (this.has(key)) this.getLong(key) else null
This is already defined in `JSONObjectExtension.kt`, you can just add `import com.onesignal.common.safeLong` to the top of this file to get this.

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/operations/impl/executors/SubscriptionOperationExecutor.kt
> +            if (rywData?.rywToken != null) {
Can be simplified to `if (rywData != null)`

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/operations/impl/executors/SubscriptionOperationExecutor.kt
> +            if (rywData?.rywToken != null) {
Can be simplified to `if (rywData != null)`

2024-10-30 21:55 UTC, jkasten2 commented on OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/operations/impl/executors/UpdateUserOperationExecutor.kt
> +                if (rywData?.rywToken != null) {
Can be simplified to `if (rywData != null)`

2024-10-31 16:25 UTC, merged